# Generated by Django 2.2.7 on 2019-11-30 18:40

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumo', ckeditor.fields.RichTextField()),
                ('conteudo', ckeditor_uploader.fields.RichTextUploadingField()),
                ('dt_cri_post', models.DateField(auto_now_add=True)),
                ('dt_pub_post', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
