# Generated by Django 2.2.7 on 2019-12-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dt_pub_post',
        ),
    ]
