# Generated by Django 2.2.7 on 2019-12-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
